services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: unity_ai
      POSTGRES_USER: unity_user
      POSTGRES_PASSWORD: unity_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - unity-ai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unity_user -d unity_ai"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./src/unity-ai.ReportingAI.Backend
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - JWT_SECRET=${JWT_SECRET}
        - METABASE_URL=${METABASE_URL}
        - METABASE_USERNAME=${METABASE_USERNAME}
        - METABASE_PASSWORD=${METABASE_PASSWORD}
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_NAME=unity_ai
        - DB_USER=unity_user
        - DB_PASSWORD=unity_pass
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - unity-ai-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./src/unity-ai.ReportingAI.Frontend
      args:
        - JWT_SECRET=${JWT_SECRET}
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - unity-ai-network

networks:
  unity-ai-network:
    driver: bridge

volumes:
  postgres_data: