services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: unity_ai
      POSTGRES_USER: unity_user
      POSTGRES_PASSWORD: unity_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - unity-ai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unity_user -d unity_ai"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  unity-ai-network:
    driver: bridge

volumes:
  postgres_data: