services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - ./embedded_schema:/app/embedded_schema
      - ./QDECOMP_examples.json:/app/QDECOMP_examples.json
      - ./sql_examples.json:/app/sql_examples.json
    networks:
      - unity-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./recap
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - unity-ai-network

networks:
  unity-ai-network:
    driver: bridge

volumes:
  embedded_schema: